"""new fields in user model

Revision ID: 449b9de5fcc6
Revises: 88b0bd519823
Create Date: 2018-10-24 20:08:51.840620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449b9de5fcc6'
down_revision = '88b0bd519823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
